### ISSUE TITLE
Protractor testing fails after install

### ISSUE THREAD

**Issue by jmsherry** [42Zavattas/generator-bangular#31]
Hi guys,
If I generate a new project (with mongodb and everything else accepted in the options) and then do `gulp e2e:update` and, after fixing the `protractor.conf.js` reference to the latest version of the seleniumServerJar (2.45.0 is scaffolded; 2.47.1 is installed), then run `gulp e2e`, I get:

```shellSession
[launcher] Process exited with error code 1
/Users/jamessherry/sites/test/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^

Error: Server terminated early with status 1
    at Error (native)
    at /Users/jamessherry/sites/test/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:204:18
    at promise.ControlFlow.runInFrame_ (/Users/jamessherry/sites/test/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at goog.defineClass.notify (/Users/jamessherry/sites/test/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at promise.Promise.notify_ (/Users/jamessherry/sites/test/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (/Users/jamessherry/sites/test/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/Users/jamessherry/sites/test/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at process._tickCallback (node.js:356:9)
[01:05:15] protractor exited with code 1
```

**Comment by jmsherry** [comment]
Having done some research it transpires that it's the seleniumServerJar itself that is having the issue. If I manually install 2.45.0 to my project then my tests run ok. I'm not sure where this bug belongs - whether to open it with gulp-protractor, protractor, selenium?! But you should know about it as it breaks the e2e...

**Comment by jmsherry** [comment]
http://stackoverflow.com/questions/33196337/gulp-protractor-selenium-webdriver-exited-status-1

Solution, if not already fixed is to install java using brew cask.

**Comment by mrobichaud21** [comment]
Thank you! I'm up and running.
