### ISSUE TITLE
Mongodb error pushing on heroku

### ISSUE THREAD

**Issue by cetrobo** [42Zavattas/generator-bangular#41]
Hi i'm try to push my app on heroku but i get error in my console

```
2016-03-11T12:11:18.926404+00:00 heroku[web.1]: State changed from crashed to starting
2016-03-11T12:11:20.408803+00:00 heroku[web.1]: Starting process with command `npm start`
2016-03-11T12:11:23.685191+00:00 app[web.1]:
2016-03-11T12:11:23.685216+00:00 app[web.1]: > portfolios@0.1.0 start /app
2016-03-11T12:11:23.685217+00:00 app[web.1]: > node server/server.js
2016-03-11T12:11:23.685217+00:00 app[web.1]:
2016-03-11T12:11:24.537123+00:00 app[web.1]:
2016-03-11T12:11:24.537134+00:00 app[web.1]: Express server listening on port 46195, in production mode.
2016-03-11T12:11:24.537135+00:00 app[web.1]:
2016-03-11T12:11:24.559264+00:00 app[web.1]:
2016-03-11T12:11:24.559298+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:242
2016-03-11T12:11:24.559310+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-03-11T12:11:24.559311+00:00 app[web.1]:                                       ^
2016-03-11T12:11:24.559340+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2016-03-11T12:11:24.559341+00:00 app[web.1]:     at Object.exports._errnoException (util.js:890:11)
2016-03-11T12:11:24.559342+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:913:20)
2016-03-11T12:11:24.559354+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14)
2016-03-11T12:11:24.576010+00:00 app[web.1]:
2016-03-11T12:11:24.588075+00:00 app[web.1]: npm ERR! Linux 3.13.0-77-generic
2016-03-11T12:11:24.588528+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-03-11T12:11:24.588795+00:00 app[web.1]: npm ERR! node v5.8.0
2016-03-11T12:11:24.589617+00:00 app[web.1]: npm ERR! npm  v3.7.3
2016-03-11T12:11:24.589809+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-03-11T12:11:24.589981+00:00 app[web.1]: npm ERR! portfolios@0.1.0 start: `node server/server.js`
2016-03-11T12:11:24.590153+00:00 app[web.1]: npm ERR! Exit status 1
2016-03-11T12:11:24.590349+00:00 app[web.1]: npm ERR!
2016-03-11T12:11:24.590551+00:00 app[web.1]: npm ERR! Failed at the portfolios@0.1.0 start script 'node server/server.js'.
2016-03-11T12:11:24.590732+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-03-11T12:11:24.590893+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the portfolios package,
2016-03-11T12:11:24.591057+00:00 app[web.1]: npm ERR! not with npm itself.
2016-03-11T12:11:24.591222+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-03-11T12:11:24.591394+00:00 app[web.1]: npm ERR!     node server/server.js
2016-03-11T12:11:24.591542+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-03-11T12:11:24.591703+00:00 app[web.1]: npm ERR!     npm bugs portfolios
2016-03-11T12:11:24.591951+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-03-11T12:11:24.592117+00:00 app[web.1]: npm ERR!     npm owner ls portfolios
2016-03-11T12:11:24.592279+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
```
any idea ?

**Comment by meriadec** [comment]
these lines
```
2016-03-11T12:11:24.559298+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:242
2016-03-11T12:11:24.559310+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-03-11T12:11:24.559311+00:00 app[web.1]:                                       ^
2016-03-11T12:11:24.559340+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
```
are saying the node process could not connect to your mongo instance (you try to connect to 127.0.0.1:27017). You should probably use a [heroku mongodb addon](https://elements.heroku.com/addons/mongolab).
