### ISSUE TITLE
'ENOENT' error on running gulp.

### ISSUE THREAD

**Issue by techguysid** [42Zavattas/generator-bangular#44]
<b> Is this because of Browser-Sync ? </b>
<i>I tried looking on web but couldn't get a appropriate solution. </i>

```
[12:58:34] Finished 'inject' after 76 ms
[12:58:34] Starting 'watch'...
[12:58:34] Finished 'watch' after 19 ms
[12:58:34] Starting 'nodemon'...
[12:58:34] [nodemon] 1.9.2
[12:58:34] [nodemon] to restart at any time, enter `rs`
[12:58:34] [nodemon] watching: *.*
[12:58:34] [nodemon] starting `node server/server.js`

Express server listening on port 9000, in development mode.

[12:58:35] Finished 'nodemon' after 872 ms
[12:58:35] Starting 'serve'...
[12:58:35] Finished 'serve' after 58 ms
[12:58:35] Starting 'default'...
[12:58:35] Finished 'default' after 6.15 μs
[BS] Proxying: http://localhost:9000
[BS] Access URLs:
 ----------------------------
 Local: http://localhost:3000
 ----------------------------
    UI: http://localhost:3001
 ----------------------------

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by techguysid** [comment]
It worked by putting a minor fix in my case.

Putting process.platform === 'linux' ? 'google-chrome' : 'google chrome' instead of process.env.BROWSER || 'google chrome', in serve.js works for Ubuntu.
